# .circleci/config.yml

version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9

    working_directory: ~/repo

    steps:
      - checkout

      # Install dependencies (if any)
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            # If you have dependencies, uncomment and adjust the following line
            # pip install -r requirements.txt

      # Run tests
      - run:
          name: Run tests
          command: |
            python -m unittest TestTriangle.py
