version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7

    steps:
      - checkout

      # Install dependencies
      - run: pip install -r requirements.txt

      # Run tests
      - run: python -m unittest TestTriangle
